### ISSUE TITLE
Problem with evauate.py

### ISSUE THREAD

**Issue by sshsurabhi** [VisualComputingInstitute/triplet-reid#43]
python3 /home/ssur/triplet-reid-master/evaluate.py  --excluder  market1501 --query_dataset  /home/ssur/triplet-reid-master/data/market1501_query.csv  --query_embeddings /home/ssur/experiments/my_experiment/market1501_query_embeddings.h5  --gallery_dataset  /home/ssur/triplet-reid-master/data/market1501_test.csv   --gallery_embeddings  /home/ssur/experiments/my_experiment/market1501_test_embeddings.h5  --metric euclidean  --filename ~/experiments/my_experiment/market1501_evaluation.json
Traceback (most recent call last):
  File "/home/ssur/triplet-reid-master/evaluate.py", line 149, in <module>
    main()
  File "/home/ssur/triplet-reid-master/evaluate.py", line 64, in main
    with h5py.File(args.query_embeddings, 'r') as f_query:
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/ssur/experiments/my_experiment/market1501_query_embeddings.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

![screenshot from 2018-06-20 13-33-19](https://user-images.githubusercontent.com/40215817/41655894-9c635d92-748e-11e8-9925-ed52bbd8ab43.png)

helo,
 I am facing some problem against evaluation... I am using latest file only. can you please explain??

Thank You

**Comment by Pandoro** [comment]
I'm sorry to be direct, but did you take the effort to read the error message from top to bottom even once? This is clearly a problem on your side and not of our code. Please just read the error message and it should be obvious what is the issue. Hence I am closing this.
