### ISSUE TITLE
ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by anilsh** [VisualComputingInstitute/triplet-reid#66]
After running embed(opts), I am getting following error:

Restoring from checkpoint: None
Traceback (most recent call last):
  File "embed_detections.py", line 247, in <module>
    main()
  File "embed_detections.py", line 208, in main
    tf.train.Saver().restore(sess, checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1534, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

Any hacks to fix it?

**Comment by anilsh** [comment]
My bad. I am calling embed.py in another project which is using your code for re-identification. The actual error is following, sorry for earlier error (I will modify that too): 

> Traceback (most recent call last):
>   File "embed.py", line 252, in <module>
>     main()
>   File "embed.py", line 213, in main
>     tf.train.Saver().restore(sess, checkpoint)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1682, in restore
>     raise ValueError("Can't load save_path when it is None.")
> ValueError: Can't load save_path when it is None.

=>  If you do not load a trained model, you are not able to create valid embeddings.
Do you mean that I can't train it from scratch? I am providing the pretrained resnet to it. 

I am trying tf 1.5.0.

**Comment by Pandoro** [comment]
You of course can train from scratch, which is typically a good idea when you are using other datasets, however, the `embed.py` script is not used for this. You will need to train your model with `train.py` and then specify a checkpoint made during training in order to load that in `embed.py`. The pretrained ResNet weights do not contain all the weights (added new embedding layers) so you cannot just restore from that in `embed.py` either.
